server:
  port: 8082

logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    shutdown:
      enabled: true